apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - name: porta-5020
    protocol: TCP
    port: 5020
    targetPort: 8001
  - name: porta-5010
    protocol: TCP
    port: 5010
    targetPort: 8000
  type: ClusterIP
