apiVersion: v1
kind: Service
metadata:
  name: atualizar-contato
  labels:
    app: atualizar-contato
spec:
  type: ClusterIP
  selector:
    app: atualizar-contato
  ports:
    - name: porta-5070
      protocol: TCP
      port: 5070
      targetPort: 8009
    - name: porta-5065
      protocol: TCP
      port: 5065
      targetPort: 8008
