apiVersion: v1
kind: Service
metadata:
  name: delete-contato
  labels:
    app: delete-contato
spec:
  type: ClusterIP
  selector:
    app: delete-contato
  ports:
    - name: porta-5080
      protocol: TCP
      port: 5080
      targetPort: 8011
    - name: porta-5075
      protocol: TCP
      port: 5075
      targetPort: 8010
