apiVersion: v1
kind: Service
metadata:
  name: mssqltools
  labels:
    app: mssqltools
spec:
  type: ClusterIP
  selector:
    app: mssqltools
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
