apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-server
  labels:
    app: mssql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-server
  template:
    metadata:
      labels:
        app: mssql-server
    spec:
      containers:
        - name: mssql-server
          image: mcr.microsoft.com/mssql/server
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: mssql-server-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-server-storage
          persistentVolumeClaim:
            claimName: mssql-server-pvc
