apiVersion: v1
kind: Service
metadata:
  name: mssql-server
  labels:
    app: mssql-server
spec:
  type: ClusterIP
  selector:
    app: mssql-server
  ports:
    - protocol: TCP
      port: 1433        # Porta para acesso ao banco de dados
      targetPort: 1433  # Porta no contêiner que o SQL Server escuta
