apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_NODE_IP_ADDRESS
              value: "0.0.0.0"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-config-volume
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
      volumes:
        - name: rabbitmq-config-volume
          configMap:
            name: rabbitmq-config
