apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 20
            periodSeconds: 10
