apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 80        # Porta exposta internamente no cluster
      targetPort: 80  # Porta no contêiner para encaminhamento do tráfego
