// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tech.Challenge.Grupo27.Infrastructure.EntityFrameworkCore;

#nullable disable

namespace Tech.Challenge.Grupo27.Infrastructure.Migrations
{
    [DbContext(typeof(TechChallengeGrupo27Context))]
    [Migration("20240526165456_RenomenandoCampoTelefone")]
    partial class RenomenandoCampoTelefone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("techchanllenge")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tech.Challenge.Grupo27.Infrastructure.Domain.Models.ContatoAggregate.ContatoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataDeAlteracao")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("DateTime");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasColumnType("Varchar(2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(80)");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Tb_Contato", "techchanllenge");
                });

            modelBuilder.Entity("Tech.Challenge.Grupo27.Infrastructure.Domain.Models.RegioesDddAggregate.RegiaoDddEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(813));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("Varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.ToTable("Tb_RegiaoDdd", "techchanllenge");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ea9e69d-2bf1-433f-9599-b3891989df55"),
                            Codigo = 11,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2200),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("421577aa-ef67-4985-9953-9d7b3859fd47"),
                            Codigo = 12,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2204),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("8fdb5915-1b3c-4319-b6aa-76a23aee5b6b"),
                            Codigo = 13,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2205),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("f5001310-7122-4d1b-afc7-e8b98b966ed8"),
                            Codigo = 14,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2206),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("a74ccbd3-6f19-46c6-8545-05b627c2119f"),
                            Codigo = 15,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2207),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("397efe48-c565-44d4-9560-9af221db15f9"),
                            Codigo = 16,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2208),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("00ff9681-0159-41ea-8173-541d16ff849e"),
                            Codigo = 17,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2209),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("aa277896-837d-467b-ad2f-5be459e9407e"),
                            Codigo = 18,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2210),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("9f7bda0f-5b8a-44e6-84b4-089f2177dcd5"),
                            Codigo = 19,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2212),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("e734b804-54eb-46d1-b182-481463312b90"),
                            Codigo = 21,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2213),
                            Descricao = "Sudeste",
                            Estado = "RJ"
                        },
                        new
                        {
                            Id = new Guid("9549ccff-bd52-42b8-8d03-b99deaa7d171"),
                            Codigo = 22,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2214),
                            Descricao = "Sudeste",
                            Estado = "RJ"
                        },
                        new
                        {
                            Id = new Guid("22db31a6-3714-45e6-bed0-d1d6857fdfd3"),
                            Codigo = 24,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2215),
                            Descricao = "Sudeste",
                            Estado = "RJ"
                        },
                        new
                        {
                            Id = new Guid("813c804d-7736-420d-aebc-536247f36f46"),
                            Codigo = 27,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2216),
                            Descricao = "Sudeste",
                            Estado = "ES"
                        },
                        new
                        {
                            Id = new Guid("da1dcf77-fffd-4df2-a5e9-0d27aaa6b178"),
                            Codigo = 28,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2217),
                            Descricao = "Sudeste",
                            Estado = "ES"
                        },
                        new
                        {
                            Id = new Guid("c4f09ac0-f48f-4bae-b824-accec26fd3c8"),
                            Codigo = 31,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2217),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("ebd4c7c1-445c-465d-a9cf-3bc7dfc0c614"),
                            Codigo = 32,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2218),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("46a65185-37f7-44ea-9682-d6bd8d2ac302"),
                            Codigo = 33,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2220),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("8e321eaf-c2eb-427b-9f52-7beb5ef8fdb7"),
                            Codigo = 34,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2222),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("9233559a-9997-405f-853a-969226fba985"),
                            Codigo = 35,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2223),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("fc221d35-eeb6-4b28-b600-8199750bf63e"),
                            Codigo = 37,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2224),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("84e0ff64-665e-4ad1-a9c7-2f61dc33c236"),
                            Codigo = 38,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2225),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("2777660a-722e-48bf-944b-84b775bca1b2"),
                            Codigo = 41,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2225),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("5aad3388-ca11-46f4-ac48-1bf333073688"),
                            Codigo = 42,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2226),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("d9644cc3-2fa2-4a66-853d-a881a7dc8b7e"),
                            Codigo = 43,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2227),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("327ff193-6ad7-4cdd-aae3-7e991abc8ae1"),
                            Codigo = 44,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2229),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("cd204c4f-73b9-4421-b832-ad1627f86a00"),
                            Codigo = 45,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2230),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("8d36e509-00f5-4e1c-8b9c-2a711a6e5087"),
                            Codigo = 46,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2231),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("3ddcf078-c92b-4c72-92ad-6360020fd606"),
                            Codigo = 47,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2232),
                            Descricao = "Sul",
                            Estado = "SC"
                        },
                        new
                        {
                            Id = new Guid("bb81d7a2-127a-4655-a5f3-3f48298fb5c9"),
                            Codigo = 48,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2232),
                            Descricao = "Sul",
                            Estado = "SC"
                        },
                        new
                        {
                            Id = new Guid("838a6ca3-41ea-42e8-93e3-52521ecccf34"),
                            Codigo = 49,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2233),
                            Descricao = "Sul",
                            Estado = "SC"
                        },
                        new
                        {
                            Id = new Guid("7a9f67a0-1d61-4201-843a-5cb094ef8dc8"),
                            Codigo = 51,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2234),
                            Descricao = "Sul",
                            Estado = "RS"
                        },
                        new
                        {
                            Id = new Guid("f1dbdb17-26f7-451c-b40a-73738f8421fd"),
                            Codigo = 53,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2235),
                            Descricao = "Sul",
                            Estado = "RS"
                        },
                        new
                        {
                            Id = new Guid("da392ba0-c9ee-42af-bef7-b9910847c85c"),
                            Codigo = 54,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2237),
                            Descricao = "Sul",
                            Estado = "RS"
                        },
                        new
                        {
                            Id = new Guid("4f8db936-7714-46e8-8d61-edb51c776782"),
                            Codigo = 55,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2237),
                            Descricao = "Sul",
                            Estado = "RS"
                        },
                        new
                        {
                            Id = new Guid("2776c47a-a9a8-4458-b187-85b87555349c"),
                            Codigo = 61,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2238),
                            Descricao = "Centro-Oeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("63cef16c-51ca-483e-aec3-f3fc5455982e"),
                            Codigo = 62,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2239),
                            Descricao = "Centro-Oeste",
                            Estado = "GO"
                        },
                        new
                        {
                            Id = new Guid("71b536dd-49b6-460f-94ad-99e7df101a62"),
                            Codigo = 64,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2240),
                            Descricao = "Centro-Oeste",
                            Estado = "GO"
                        },
                        new
                        {
                            Id = new Guid("f628bb38-4604-4c92-83de-68ebf7983048"),
                            Codigo = 65,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2241),
                            Descricao = "Centro-Oeste",
                            Estado = "MT"
                        },
                        new
                        {
                            Id = new Guid("205971c1-0508-4c08-ba1e-012554df53f8"),
                            Codigo = 66,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2282),
                            Descricao = "Centro-Oeste",
                            Estado = "MT"
                        },
                        new
                        {
                            Id = new Guid("4a81bbda-69ad-47b9-b54c-b02c00858649"),
                            Codigo = 67,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2282),
                            Descricao = "Centro-Oeste",
                            Estado = "MS"
                        },
                        new
                        {
                            Id = new Guid("111c8f95-f78b-4565-9a71-65480402181b"),
                            Codigo = 63,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2285),
                            Descricao = "Norte",
                            Estado = "TO"
                        },
                        new
                        {
                            Id = new Guid("dd00934a-8c19-40b8-8d42-12657b1afd27"),
                            Codigo = 68,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2285),
                            Descricao = "Norte",
                            Estado = "AC"
                        },
                        new
                        {
                            Id = new Guid("36891fae-dc09-4e7a-8e7f-f1f800029a18"),
                            Codigo = 69,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2286),
                            Descricao = "Norte",
                            Estado = "RO"
                        },
                        new
                        {
                            Id = new Guid("9f77eff5-bb3f-4580-9e25-da0c902da1c6"),
                            Codigo = 96,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2287),
                            Descricao = "Norte",
                            Estado = "AP"
                        },
                        new
                        {
                            Id = new Guid("ee133b4f-c573-4699-99ea-125dea13ba63"),
                            Codigo = 92,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2288),
                            Descricao = "Norte",
                            Estado = "AM"
                        },
                        new
                        {
                            Id = new Guid("18a75e3b-ee38-4244-923a-459f37a959cf"),
                            Codigo = 97,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2289),
                            Descricao = "Norte",
                            Estado = "AM"
                        },
                        new
                        {
                            Id = new Guid("e42250f4-b70f-4148-8b75-5e361b054ad1"),
                            Codigo = 91,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2289),
                            Descricao = "Norte",
                            Estado = "PA"
                        },
                        new
                        {
                            Id = new Guid("43a8f663-6d40-4851-be89-e1aa032511cf"),
                            Codigo = 93,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2290),
                            Descricao = "Norte",
                            Estado = "PA"
                        },
                        new
                        {
                            Id = new Guid("00fd5ecf-6842-4a65-a90c-37b266e23d7a"),
                            Codigo = 94,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2292),
                            Descricao = "Norte",
                            Estado = "PA"
                        },
                        new
                        {
                            Id = new Guid("6928d223-35d3-4f68-b7a1-13e4c53f3bee"),
                            Codigo = 95,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2293),
                            Descricao = "Norte",
                            Estado = "RR"
                        },
                        new
                        {
                            Id = new Guid("3382acdf-2828-49c8-b38c-a352481615bd"),
                            Codigo = 71,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2294),
                            Descricao = "Nordeste",
                            Estado = "BA"
                        },
                        new
                        {
                            Id = new Guid("cd4ae77c-ae0d-48ce-859f-176b9b9c533d"),
                            Codigo = 73,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2295),
                            Descricao = "Nordeste",
                            Estado = "BA"
                        },
                        new
                        {
                            Id = new Guid("163887b1-224b-44e0-9a4a-98065196f0f3"),
                            Codigo = 74,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2296),
                            Descricao = "Nordeste",
                            Estado = "BA"
                        },
                        new
                        {
                            Id = new Guid("b8612cbd-b835-4f63-b3a7-9105b747ac2e"),
                            Codigo = 75,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2296),
                            Descricao = "Nordeste",
                            Estado = "BA"
                        },
                        new
                        {
                            Id = new Guid("e08b3d7f-5270-4ec2-9ecf-f0b083dff7fc"),
                            Codigo = 77,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2297),
                            Descricao = "Nordeste",
                            Estado = "BA"
                        },
                        new
                        {
                            Id = new Guid("c177db01-e964-42d8-bfa3-b644ef9c5a1c"),
                            Codigo = 85,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2298),
                            Descricao = "Nordeste",
                            Estado = "CE"
                        },
                        new
                        {
                            Id = new Guid("4638316f-773e-4a97-9d6c-f5cb2b04d759"),
                            Codigo = 88,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2300),
                            Descricao = "Nordeste",
                            Estado = "CE"
                        },
                        new
                        {
                            Id = new Guid("3b826a8d-b6fd-4897-b169-2b7fa6cf1f7d"),
                            Codigo = 98,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2301),
                            Descricao = "Nordeste",
                            Estado = "MA"
                        },
                        new
                        {
                            Id = new Guid("228c598b-db27-41b1-978d-4980ab51043e"),
                            Codigo = 99,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2302),
                            Descricao = "Nordeste",
                            Estado = "MA"
                        },
                        new
                        {
                            Id = new Guid("fb346fd5-be09-4cd4-951c-8cf6b1e4c797"),
                            Codigo = 83,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2302),
                            Descricao = "Nordeste",
                            Estado = "PB"
                        },
                        new
                        {
                            Id = new Guid("680f35a7-fce9-434f-9446-03203a011edb"),
                            Codigo = 81,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2303),
                            Descricao = "Nordeste",
                            Estado = "PE"
                        },
                        new
                        {
                            Id = new Guid("d6cd24b7-0ead-4060-932e-5c7aee17a9a6"),
                            Codigo = 87,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2304),
                            Descricao = "Nordeste",
                            Estado = "PE"
                        },
                        new
                        {
                            Id = new Guid("43c30c18-e927-426f-b7d3-8edd418bf46c"),
                            Codigo = 86,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2305),
                            Descricao = "Nordeste",
                            Estado = "PI"
                        },
                        new
                        {
                            Id = new Guid("25ad072d-c972-4c42-a112-756fd29f4d29"),
                            Codigo = 89,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2306),
                            Descricao = "Nordeste",
                            Estado = "PI"
                        },
                        new
                        {
                            Id = new Guid("91dd4a92-abc4-4a25-86f8-b277bcc8248f"),
                            Codigo = 84,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2308),
                            Descricao = "Nordeste",
                            Estado = "RN"
                        },
                        new
                        {
                            Id = new Guid("309b45d0-4bd6-4988-a33f-77adfddefb42"),
                            Codigo = 82,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2308),
                            Descricao = "Nordeste",
                            Estado = "AL"
                        },
                        new
                        {
                            Id = new Guid("0c2c0228-9e93-4b0d-a401-b6912dac718f"),
                            Codigo = 79,
                            DataDeCriacao = new DateTime(2024, 5, 26, 16, 54, 56, 359, DateTimeKind.Utc).AddTicks(2309),
                            Descricao = "Nordeste",
                            Estado = "SE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
