// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tech.Challenge.Grupo27.Infrastructure.EntityFrameworkCore;

#nullable disable

namespace Tech.Challenge.Grupo27.Infrastructure.Migrations
{
    [DbContext(typeof(TechChallengeGrupo27Context))]
    [Migration("20240418030720_BaseInicial")]
    partial class BaseInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("techchanllenge")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tech.Challenge.Grupo27.Infrastructure.Domain.Models.ContatoAggregate.ContatoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataDeAlteracao")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("DateTime");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasColumnType("Varchar(2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(80)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Tb_Contato", "techchanllenge");
                });
#pragma warning restore 612, 618
        }
    }
}
