// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tech.Challenge.Grupo27.Infrastructure.EntityFrameworkCore;

#nullable disable

namespace Tech.Challenge.Grupo27.Infrastructure.Migrations
{
    [DbContext(typeof(TechChallengeGrupo27Context))]
    [Migration("20240501004452_CriarTabelaRegiaoDdd")]
    partial class CriarTabelaRegiaoDdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("techchanllenge")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tech.Challenge.Grupo27.Infrastructure.Domain.Models.ContatoAggregate.ContatoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataDeAlteracao")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("DateTime");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasColumnType("Varchar(2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(80)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Tb_Contato", "techchanllenge");
                });

            modelBuilder.Entity("Tech.Challenge.Grupo27.Infrastructure.Domain.Models.RegioesDddAggregate.RegiaoDddEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 5, 1, 0, 44, 52, 505, DateTimeKind.Utc).AddTicks(9049));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("Varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.ToTable("Tb_RegiaoDdd", "techchanllenge");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64680cc5-908f-47c5-8da4-4f1af348cdcf"),
                            Codigo = 11,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1197),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("59949c4a-046b-4aef-bd42-56040862d827"),
                            Codigo = 12,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1200),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("3641630e-86a3-451d-affa-23965228c9c4"),
                            Codigo = 13,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1201),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("aa07ec60-9023-4749-9e62-dcac760f26b0"),
                            Codigo = 14,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1202),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("beac6cf9-ccfc-451e-8d77-4216881554e4"),
                            Codigo = 15,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1203),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("bdcd959b-db78-4906-9315-9553e11cb601"),
                            Codigo = 16,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1205),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("704a2903-c63b-4edd-9460-45739c1fa958"),
                            Codigo = 17,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1206),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("157329da-793c-4be1-94e8-995df5155938"),
                            Codigo = 18,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1216),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("56c2c878-d4b4-401e-b8cd-aec150b046a8"),
                            Codigo = 19,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1217),
                            Descricao = "Sudeste",
                            Estado = "SP"
                        },
                        new
                        {
                            Id = new Guid("62abcc16-660f-4dc1-8756-48adc3418c66"),
                            Codigo = 21,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1218),
                            Descricao = "Sudeste",
                            Estado = "RJ"
                        },
                        new
                        {
                            Id = new Guid("249cc8ca-0b77-47f6-a8a5-f23758854907"),
                            Codigo = 22,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1219),
                            Descricao = "Sudeste",
                            Estado = "RJ"
                        },
                        new
                        {
                            Id = new Guid("35b68b80-6311-449d-8cc5-9b707d55bc5d"),
                            Codigo = 24,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1220),
                            Descricao = "Sudeste",
                            Estado = "RJ"
                        },
                        new
                        {
                            Id = new Guid("a18aed3b-30a7-4d9e-bd43-fdd74b6246cd"),
                            Codigo = 27,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1221),
                            Descricao = "Sudeste",
                            Estado = "ES"
                        },
                        new
                        {
                            Id = new Guid("93282d5c-b803-4581-a7d8-add528d7a199"),
                            Codigo = 28,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1222),
                            Descricao = "Sudeste",
                            Estado = "ES"
                        },
                        new
                        {
                            Id = new Guid("b93cd4f2-219e-4c55-9609-12e72f010a6c"),
                            Codigo = 31,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1223),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("fc337cca-c279-4885-baeb-48006096afcf"),
                            Codigo = 32,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1226),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("6a6ba9ed-ca1d-4ff7-835e-f5d87b7e1a11"),
                            Codigo = 33,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1262),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("d70092d6-7fae-430e-ba02-a14b5bc42f52"),
                            Codigo = 34,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1263),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("b41fd644-eaaa-4855-8145-e8d157ca017f"),
                            Codigo = 35,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1264),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("1707bf2c-eb82-4428-b11a-ef3541e50222"),
                            Codigo = 37,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1265),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("e2a7f7a2-0777-42df-9008-f904f6d85dc9"),
                            Codigo = 38,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1266),
                            Descricao = "Sudeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("ad643600-348e-4620-9817-308282f1b45f"),
                            Codigo = 41,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1266),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("9fb12816-1d16-41cd-9e79-d929f4bda83a"),
                            Codigo = 42,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1267),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("e5e41bc0-7428-46bc-8a2a-9468202bbbeb"),
                            Codigo = 43,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1270),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("35a7e32c-1f28-4e6d-955c-631acf59fb75"),
                            Codigo = 44,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1271),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("d4debec4-d8ed-4360-9b8e-92f609ce2679"),
                            Codigo = 45,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1272),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("5490b2c3-7f99-4c44-8a07-41b0ac6bec6f"),
                            Codigo = 46,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1273),
                            Descricao = "Sul",
                            Estado = "PR"
                        },
                        new
                        {
                            Id = new Guid("0eed422d-15b6-472f-a9ef-41dce135994e"),
                            Codigo = 47,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1274),
                            Descricao = "Sul",
                            Estado = "SC"
                        },
                        new
                        {
                            Id = new Guid("363b50c0-46a8-4290-af2d-21d2b1c3232c"),
                            Codigo = 48,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1275),
                            Descricao = "Sul",
                            Estado = "SC"
                        },
                        new
                        {
                            Id = new Guid("6faae7be-0399-4aef-a683-f75088234e2c"),
                            Codigo = 49,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1275),
                            Descricao = "Sul",
                            Estado = "SC"
                        },
                        new
                        {
                            Id = new Guid("3307e912-fa12-4600-9970-c055f3f5a058"),
                            Codigo = 51,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1276),
                            Descricao = "Sul",
                            Estado = "RS"
                        },
                        new
                        {
                            Id = new Guid("3df42706-728d-498c-8567-8f5891e8dfe1"),
                            Codigo = 53,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1280),
                            Descricao = "Sul",
                            Estado = "RS"
                        },
                        new
                        {
                            Id = new Guid("9aa8d2ef-fb90-40c0-88e2-22c9e6bd9046"),
                            Codigo = 54,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1280),
                            Descricao = "Sul",
                            Estado = "RS"
                        },
                        new
                        {
                            Id = new Guid("6bf8ae60-cf2f-41ed-9b80-d5aa726effc7"),
                            Codigo = 55,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1281),
                            Descricao = "Sul",
                            Estado = "RS"
                        },
                        new
                        {
                            Id = new Guid("0589f76f-cca7-4f8b-bfe6-81528fb284b0"),
                            Codigo = 61,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1282),
                            Descricao = "Centro-Oeste",
                            Estado = "MG"
                        },
                        new
                        {
                            Id = new Guid("bf97db69-908e-4a69-b2e6-c14a652662e7"),
                            Codigo = 62,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1283),
                            Descricao = "Centro-Oeste",
                            Estado = "GO"
                        },
                        new
                        {
                            Id = new Guid("cb2a0e90-39ee-4e74-800a-1bbc0effaa44"),
                            Codigo = 64,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1284),
                            Descricao = "Centro-Oeste",
                            Estado = "GO"
                        },
                        new
                        {
                            Id = new Guid("138b7ed3-e4a5-47bc-89fa-7116eded119f"),
                            Codigo = 65,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1285),
                            Descricao = "Centro-Oeste",
                            Estado = "MT"
                        },
                        new
                        {
                            Id = new Guid("b9211ec6-1220-4e33-999e-8cf869d41dc2"),
                            Codigo = 66,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1286),
                            Descricao = "Centro-Oeste",
                            Estado = "MT"
                        },
                        new
                        {
                            Id = new Guid("8c325796-8046-4dff-b798-0d70798b9150"),
                            Codigo = 67,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1289),
                            Descricao = "Centro-Oeste",
                            Estado = "MS"
                        },
                        new
                        {
                            Id = new Guid("bf2e0270-4db0-427f-ac69-3afe5610d471"),
                            Codigo = 63,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1290),
                            Descricao = "Norte",
                            Estado = "TO"
                        },
                        new
                        {
                            Id = new Guid("f3ce76c6-c23c-4b4d-827e-04cc71479604"),
                            Codigo = 68,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1290),
                            Descricao = "Norte",
                            Estado = "AC"
                        },
                        new
                        {
                            Id = new Guid("96d5748b-2b80-4fbb-97f1-d7b6200457d9"),
                            Codigo = 69,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1291),
                            Descricao = "Norte",
                            Estado = "RO"
                        },
                        new
                        {
                            Id = new Guid("2e1a6526-2840-4e48-916c-ad63962dd702"),
                            Codigo = 96,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1292),
                            Descricao = "Norte",
                            Estado = "AP"
                        },
                        new
                        {
                            Id = new Guid("3905cc59-a07c-41c4-a38b-7104e52fcc1f"),
                            Codigo = 92,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1293),
                            Descricao = "Norte",
                            Estado = "AM"
                        },
                        new
                        {
                            Id = new Guid("50410a0e-d7f0-40db-8207-d72ef5fd8740"),
                            Codigo = 97,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1294),
                            Descricao = "Norte",
                            Estado = "AM"
                        },
                        new
                        {
                            Id = new Guid("7d3f2ef0-9717-4799-b138-1937afecc90a"),
                            Codigo = 91,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1295),
                            Descricao = "Norte",
                            Estado = "PA"
                        },
                        new
                        {
                            Id = new Guid("a292cb13-e393-4279-9258-32ac278f97ed"),
                            Codigo = 93,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1297),
                            Descricao = "Norte",
                            Estado = "PA"
                        },
                        new
                        {
                            Id = new Guid("f2f23922-620a-4c2d-86b9-faa5a71029ea"),
                            Codigo = 94,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1298),
                            Descricao = "Norte",
                            Estado = "PA"
                        },
                        new
                        {
                            Id = new Guid("cd446ee0-b75a-40be-adb9-4c6c1a4d3719"),
                            Codigo = 95,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1299),
                            Descricao = "Norte",
                            Estado = "RR"
                        },
                        new
                        {
                            Id = new Guid("ba63163f-61e7-47a5-8386-24ee269d7f9f"),
                            Codigo = 71,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1300),
                            Descricao = "Nordeste",
                            Estado = "BA"
                        },
                        new
                        {
                            Id = new Guid("2479c04d-ccb8-4e41-8fda-17cf33bd3e75"),
                            Codigo = 73,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1301),
                            Descricao = "Nordeste",
                            Estado = "BA"
                        },
                        new
                        {
                            Id = new Guid("b3b086ea-2125-4198-ab7f-17f78f4dcbf2"),
                            Codigo = 74,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1302),
                            Descricao = "Nordeste",
                            Estado = "BA"
                        },
                        new
                        {
                            Id = new Guid("3136e301-6608-4f6a-8d51-6cd72a606aa0"),
                            Codigo = 75,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1303),
                            Descricao = "Nordeste",
                            Estado = "BA"
                        },
                        new
                        {
                            Id = new Guid("cb2ce430-1d3e-4c9f-951e-4e5e86042494"),
                            Codigo = 77,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1304),
                            Descricao = "Nordeste",
                            Estado = "BA"
                        },
                        new
                        {
                            Id = new Guid("4d4bc72f-fd26-4fb1-8e72-2161d58c1a15"),
                            Codigo = 85,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1306),
                            Descricao = "Nordeste",
                            Estado = "CE"
                        },
                        new
                        {
                            Id = new Guid("b860f49b-d952-4e9f-a004-310759ed7e2d"),
                            Codigo = 88,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1307),
                            Descricao = "Nordeste",
                            Estado = "CE"
                        },
                        new
                        {
                            Id = new Guid("721e10fd-fa65-4363-9075-5fab8bbf9216"),
                            Codigo = 98,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1308),
                            Descricao = "Nordeste",
                            Estado = "MA"
                        },
                        new
                        {
                            Id = new Guid("846aa5cb-c149-41b2-9279-d03b4dd4e607"),
                            Codigo = 99,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1309),
                            Descricao = "Nordeste",
                            Estado = "MA"
                        },
                        new
                        {
                            Id = new Guid("82473912-6cfa-4f6d-ac6a-e8aa112d8268"),
                            Codigo = 83,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1310),
                            Descricao = "Nordeste",
                            Estado = "PB"
                        },
                        new
                        {
                            Id = new Guid("c6a4756c-e952-490a-a5bb-a069e2965053"),
                            Codigo = 81,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1311),
                            Descricao = "Nordeste",
                            Estado = "PE"
                        },
                        new
                        {
                            Id = new Guid("c63f095b-f0db-4f37-a476-25c4388557c0"),
                            Codigo = 87,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1312),
                            Descricao = "Nordeste",
                            Estado = "PE"
                        },
                        new
                        {
                            Id = new Guid("86e527e3-e71b-4659-b8c8-42d2380b8f76"),
                            Codigo = 86,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1313),
                            Descricao = "Nordeste",
                            Estado = "PI"
                        },
                        new
                        {
                            Id = new Guid("27065733-0912-4d1d-aa13-43de66180b06"),
                            Codigo = 89,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1315),
                            Descricao = "Nordeste",
                            Estado = "PI"
                        },
                        new
                        {
                            Id = new Guid("6a986fe4-573c-497b-996f-959e81eed721"),
                            Codigo = 84,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1316),
                            Descricao = "Nordeste",
                            Estado = "RN"
                        },
                        new
                        {
                            Id = new Guid("a04e03a9-371a-44d8-9666-e0fc8538bf4d"),
                            Codigo = 82,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1317),
                            Descricao = "Nordeste",
                            Estado = "AL"
                        },
                        new
                        {
                            Id = new Guid("391e1a45-0c3e-462f-8390-51711129847f"),
                            Codigo = 79,
                            DataDeCriacao = new DateTime(2024, 5, 1, 0, 44, 52, 506, DateTimeKind.Utc).AddTicks(1318),
                            Descricao = "Nordeste",
                            Estado = "SE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
